package workspace

import (
	"encoding/json"
	"fmt"
	"mals/internal/model"
	"strings"

	"github.com/invopop/jsonschema"
)

func generateSchema[T any]() any {
	reflector := jsonschema.Reflector{
		AllowAdditionalProperties: false,
		DoNotReference:            true,
	}
	var v T
	schema := reflector.Reflect(v)
	return schema
}

func getPosition(content string, line, char uint32) uint64 {
	lines := strings.Split(content, "\n")

	if line >= uint32(len(lines)) {
		return uint64(len(content))
	}

	var position uint64
	// Add lengths of all previous lines (including newlines)
	for i := range line {
		position += uint64(len(lines[i])) + 1 // +1 for newline
	}

	// Add column position (0-based)
	if char <= uint32(len(lines[line])) {
		position += uint64(char)
	} else {
		position += uint64(len(lines[line]))
	}

	return position
}

func getLastNPositionChars(content string, position uint64, n uint64) string {
	contentLen := uint64(len(content))
	if position > contentLen {
		position = contentLen
	}

	var start uint64
	if position > n {
		start = position - n
	} else {
		start = 0
	}

	return content[start:position]
}

func GetLastNChars(content string, line, char uint32, n uint64) string {
	position := getPosition(content, line, char)
	return getLastNPositionChars(content, position, n)
}

// long performing task
func (w *Workspace) GenerateCompletionList(filepath string, position Position) ([]CompletionItem, error) {
	documentText, exists := w.Documents[filepath]
	if !exists {
		return nil, fmt.Errorf("document %s doesn't exist", filepath)
	}

	// TODO: change when deleging to real LSP
	// words := strings.Fields(documentText)
	// slices.Sort(words)
	// words = slices.Compact(words)
	// words = append(words, filepath)

	currentContext := GetLastNChars(documentText, position.Line, position.Char, 200)

	prompt := GetCompletionPrompt(documentText, currentContext)
	schema := generateSchema[[]string]()

	request := model.NewModelRequest(
		prompt,
		schema,
		"completion_items",
		"Generated completion items",
	)

	task := model.NewModelTask(request, w.modelRespCh)
	w.model.SubmitTask(task)

	resp := <-w.modelRespCh

	if resp.Error != nil {
		return nil, resp.Error
	}

	var respItemArray []string
	if err := json.Unmarshal([]byte(resp.Text), &respItemArray); err != nil {
		return nil, fmt.Errorf("%s, while parsing %s", err, resp.Text)
	}

	items := make([]CompletionItem, len(respItemArray))
	for i, s := range respItemArray {
		items[i] = CompletionItem{
			Label:         s,
			Detail:        fmt.Sprintf("%s (%d)", s, i),
			Documentation: "Generated by LLM",
		}
	}

	return items, nil
}
