package middleware

import (
	"encoding/json"
	"fmt"
	"mals/internal/lsp/protocol"
	"mals/internal/middleware/document"
	"mals/internal/model"
	"mals/internal/scope"
	"mals/internal/usage"
	"mals/internal/util"
	"mals/pkg/config"
	"sync"

	"github.com/invopop/jsonschema"
)

const (
	completionTemplate = `
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are an intelligent autocompletion engine. Your task is to suggest relevant text completions based on document context.

Rules:
- Analyze the document context and writing style
- Generate 3-5 contextually appropriate completions
- Match the existing tone and style
- Provide completions of varying lengths (words to phrases)
- Return ONLY a valid JSON array of strings
- No explanations, no additional text

<|eot_id|><|start_header_id|>user<|end_header_id|>

Document text: The weather today is quite nice. I think I'll go for a walk in the park and maybe stop by the
Current context: "I think I'll go for a walk in the park and maybe stop by the"

<|eot_id|><|start_header_id|>assistant<|end_header_id|>

["coffee shop", "library", "store to buy groceries", "lake to feed the ducks"]

<|eot_id|><|start_header_id|>user<|end_header_id|>

Document text: She opened her laptop and started typing her report. The first chapter discussed the importance of renewable energy sources. Solar panels and wind turbines are becoming more
Current context: "Solar panels and wind turbines are becoming more"

<|eot_id|><|start_header_id|>assistant<|end_header_id|>

["efficient", "affordable each year", "popular worldwide", "cost-effective solutions", "widely adopted"]

<|eot_id|><|start_header_id|>user<|end_header_id|>

Document text:
%s

Current context:
%s

<|eot_id|><|start_header_id|>assistant<|end_header_id|>
`
)

func completionPrompt(documentContext string, currentContext string) string {
	prompt := fmt.Sprintf(completionTemplate, documentContext, currentContext)
	return prompt
}

func completionSchema[T any]() any {
	reflector := jsonschema.Reflector{
		AllowAdditionalProperties: false,
		DoNotReference:            true,
	}
	var v T
	schema := reflector.Reflect(v)
	return schema
}

func (s *Middleware) completionStepModel(params *protocol.CompletionParams, document *document.Document, step *config.Step) (*protocol.CompletionList, error) {

	modelName := step.Kind.(*config.StepKindModel).Name

	// TODO: handle other scopes
	if step.Scope != "global" {
		s.plane.Warnf("step %T %v scope %v unsupported", step, step, step.Scope)
	}

	modelFullname, token, err := s.plane.ScopeModelAcquire(modelName, scope.NewScopeGlobal())
	if err != nil {
		s.plane.Warnf("step %T %v: %v", step, step, err)
		return nil, err
	}
	defer s.plane.ScopeModelRelease(modelFullname, token)

	taskText := completionPrompt(
		document.Text(),
		document.LastNChars(params.Position.Line, params.Position.Character, 200),
	)
	task := model.NewTask(
		taskText,
		completionSchema[[]string](),
		"completion_items",
		"Generated completion items",
	)

	text, err := s.plane.TaskExecClient(modelFullname, task, s.client)
	if err != nil {
		s.plane.Warnf("step %T %v: %v", step, step, err)
		return nil, err
	}

	var resItems []string
	if err := json.Unmarshal([]byte(text), &resItems); err != nil {
		return nil, fmt.Errorf("step %T %v: %v", step, step, err)
	}

	items := make([]protocol.CompletionItem, len(resItems))
	for i, s := range resItems {
		items[i] = protocol.CompletionItem{
			Label:         s,
			Detail:        fmt.Sprintf("%v (%v)", s, i),
			Documentation: &protocol.Or_CompletionItem_documentation{Value: fmt.Sprintf("Generated by %v", modelName)},
		}
	}

	// TODO: process all the steps
	result := &protocol.CompletionList{
		IsIncomplete: false,
		Items:        items,
	}

	return result, nil
}

func (s *Middleware) completionWorkflow(params *protocol.CompletionParams, document *document.Document, workflow *config.Workflow) (*protocol.CompletionList, error) {
	var result *protocol.CompletionList

	for _, step := range workflow.Steps {
		switch step.Kind.(type) {

		case *config.StepKindModel:
			if r, err := s.completionStepModel(params, document, step); err != nil {
				return nil, err
			} else {
				result = r
			}

		default:
			err := fmt.Errorf("unhandled step %T %v", step, step)
			s.plane.Warnf("%v", err)
			return nil, err
		}
	}

	return result, nil
}

func (s *Middleware) TextDocumentCompletion(params *protocol.CompletionParams) (*protocol.CompletionList, error) {
	uri := params.TextDocument.URI

	workspaces := s.workspaceFindAll(uri)

	if len(workspaces) == 0 {
		s.plane.Warnf("%v: file %v is not bound to any workspace", s.Name(), uri)
	}

	var wg sync.WaitGroup

	listCh := make(chan *protocol.CompletionList)

	for _, workspace := range workspaces {
		document := s.documentGet(workspace, uri)
		if document == nil {
			continue
		}

		s.plane.Infof("%T %v: workspace %v document %v: completion", s, s.Name(), workspace.name, document.Uri())

		usages := s.plane.UsageGetFilteredClient(
			usage.ConditionFilter{Filetype: nil, Path: util.Ptr(document.Uri())},
			usage.EventFilter{Event: util.Ptr(config.EventTextDocumentCompletion)}, s.Name())

		for _, usage := range usages {
			wg.Go(func() {
				list, err := s.completionWorkflow(params, document, usage.Workflow)

				if err != nil {
					s.plane.Errorf("%T %v: workspace %v %v", s, s.Name(), workspace.name, err)
					return
				}

				listCh <- list
			})
		}
	}

	go func() {
		wg.Wait()
		close(listCh)
	}()

	var result protocol.CompletionList

	for list := range listCh {
		if list != nil {
			result.Items = append(result.Items, list.Items...)
			result.IsIncomplete = result.IsIncomplete || list.IsIncomplete
		}
	}

	return &result, nil
}
